// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLPNpiwvkyT4slkcupP8BicYXWcLjW2CU',
    appId: '1:233978887224:web:48fc0caf4dccf750f6facd',
    messagingSenderId: '233978887224',
    projectId: 'ddffd-6da33',
    authDomain: 'ddffd-6da33.firebaseapp.com',
    storageBucket: 'ddffd-6da33.appspot.com',
    measurementId: 'G-ZLFBCRGCV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc0wj1Q-lNBLXLY4XpfGOYU2JoUsSRGb0',
    appId: '1:233978887224:android:bf6b24c0e4717a15f6facd',
    messagingSenderId: '233978887224',
    projectId: 'ddffd-6da33',
    storageBucket: 'ddffd-6da33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-jqBqheRcp_YcWcn4pHX0ZOpDOrDaQrI',
    appId: '1:233978887224:ios:3180c6c7e1cea9a1f6facd',
    messagingSenderId: '233978887224',
    projectId: 'ddffd-6da33',
    storageBucket: 'ddffd-6da33.appspot.com',
    iosBundleId: 'com.example.beautyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-jqBqheRcp_YcWcn4pHX0ZOpDOrDaQrI',
    appId: '1:233978887224:ios:3180c6c7e1cea9a1f6facd',
    messagingSenderId: '233978887224',
    projectId: 'ddffd-6da33',
    storageBucket: 'ddffd-6da33.appspot.com',
    iosBundleId: 'com.example.beautyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLPNpiwvkyT4slkcupP8BicYXWcLjW2CU',
    appId: '1:233978887224:web:6b34c839534fe145f6facd',
    messagingSenderId: '233978887224',
    projectId: 'ddffd-6da33',
    authDomain: 'ddffd-6da33.firebaseapp.com',
    storageBucket: 'ddffd-6da33.appspot.com',
    measurementId: 'G-QN2S1NZ7N3',
  );

}